### ISSUE TITLE
Content Not Displaying Properly on Main and Draw Pages

### ISSUE THREAD

**Issue by jitendrakinet** [xkeshav/canvas#4]
**Issue**:
The entire content on the main page and draw page is not being displayed. unable to view the full content, which is affecting the usability of these pages.

**Proposed Solutions**:
- Ensure the whole content is visible on both the main page and draw page.
- Add a scrollbar to allow users to scroll through the content if it exceeds the viewport size.

**Environment**:
- Browser: Chrome
- Operating System: Windows 11
- Viewport Size: 1536px × 695px

**Steps to Reproduce**:
1. Navigate to the main page or draw page.
2. Attempt to view all content on the page.

**Expected Result**:
The entire content should be visible, either by fitting within the viewport or through the use of a scrollbar.

**Actual Result**:
The content is partially hidden, with no way to access the hidden portions.

**Comment by xkeshav** [comment]
fixed the issue
